### ISSUE TITLE
Add hackups to Meetup.com

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#100]
After our discussion last night I think it's important to get our hackups added to meetup.com.

@seanhealy as you're running these I've assigned this to you but please let me know if there's anything I can do to help.

**Comment by CAYdenberg** [comment]
@snostorm Just realized I do not have your email address. Can you post it here or send me an email at ydenberg@gmail.com?

**Comment by MarkBennett** [comment]
I can help with this! Check your email. 😉
