### ISSUE TITLE
Thursday, September 7, 2017 Meetup

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#101]
## To Do
- [ ] Arrange MC (WHO?)
- [ ] Arrange food (WHERE?)
- [ ] Arrange meetup recording (WHO?)
- [ ] Do pre-interview with speakers 2 weeks prior to meetup
- [ ] Review and tweak preroll slides
- [ ] Create notes (add a link below)
- [ ] Update speakers in notes
- [ ] Update events in notes
- [ ] Update next meetup in notes
- [ ] Update news and software releases in notes
- [ ] Update job listings
- [ ] Update introduction question
- [ ] Mail out 3 day before meetup reminder
- [ ] Update meetup.com
- [ ] Check-in with speakers 3 days prior to meetup
- [ ] Tweet out 3 day before meetup link
- [ ] Tweet out 1 day before meetup link
- [ ] Tweet day of meetup link

## See also

- [Exchange.js Speakers](https://docs.google.com/spreadsheets/d/1_FOG1K_fUbTlNvqT9hjihiXYt9AhPkZxW6tfZN858VU/edit?usp=sharing)
- [Preroll Slides](https://exchangejs.github.io/exchangejs-preroll)
- Meetup slides (ADD A LINK!)
- [Past talks](https://drive.google.com/open?id=0B1angknldByTSUx0eFJsN0VOcjQ)

/cc @ExchangeJS/organizers

**Comment by dlolsen** [comment]
I've been looking into food. Italian Centre can do sandwich trays. They just need 48hrs notice. Not quite sure how many trays to get, or if you wanted something fancier on the first meetup. Was thinking 2 [sandwich trays](http://www.italiancentre.ca/panini-sandwich) & some [veggies](http://www.italiancentre.ca/crudite-and-dip).

Is canned pop good for drinks? [Fanta with Barks party pack](https://www.realcanadiansuperstore.ca/Food/Drinks/Soft-Drinks/18-%26-Up-Packs/Flavour-Play-Pack/p/20566292_C24?isPDPFlow=Y) is cheap. Or an assortment of [San Pellegrino](https://www.realcanadiansuperstore.ca/search/1504049189347/page/~item/san+pelegrino/~sort/recommended/~selected/true) up the game a bit and we would have $ 0.67 left according to [Food Planning spreadsheet](https://docs.google.com/spreadsheets/d/1L5JsGDs-1_Nk4bzJPo4KSpef463A8ED0RL9zII_KhW8).

Do we need to do a certain amount of veggie sandwiches? Not sure what the demand will be.

**Comment by MarkBennett** [comment]
Sure @dlolsen. That should be good. Two of the large sandwich trays should be enough, plus some veggies. Might as well get the San Pellegrino too. Can you cost that out and see if it's over $200? Maybe use your judgement and see if we can hit the $200 mark.

**Comment by dlolsen** [comment]
@MarkBennett It's coming in at $199.33 … with the San Pellegrino.

**Comment by MarkBennett** [comment]
Do we need someone to pick it up?
