### ISSUE TITLE
Setup bank accounts for Dev Edmonton

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#102]
We need to determine our banking needs then setup the most cost effective solution possible.

**Comment by dlolsen** [comment]
@MarkBennett I did a cursory search and it looks like the big banks all offer similar plans. About $2.50/month for account fees with limited transactions (like 10-20) and only a couple in branch transactions. I bank with TD for my business

I'll also peek around at credit unions and other options.

Approximately what kind of monthly transaction volume was done in the past?

**Comment by MarkBennett** [comment]
In the past, it's been pretty low. Here's the transaction from our ledger from 2016-17:

https://docs.google.com/spreadsheets/d/1Ozvk4DwQWYi0i1VXy5O0NicNYB5cuf-_9pkMnncL_Ko/edit?usp=sharing

There were 13 transactions in total, so 1 sometimes 2 per month.
