### ISSUE TITLE
Oct 2017 Meetup

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#104]
## To Do
- [X] Arrange MC (Sean O.)
- [x] Arrange food (WHERE?)
- [ ] Arrange meetup recording (WHO?)
- [ ] Do pre-interview with speakers 2 weeks prior to meetup
- [ ] Review and tweak preroll slides
- [ ] Create notes ([slides](https://docs.google.com/presentation/d/1DH0pD5km1YVCrMRqdTt9AHbgQW84FNZqxj9mcjmCJA0/edit#slide=id.p))
- [ ] Update speakers in notes
- [ ] Update events in notes
- [ ] Update next meetup in notes
- [ ] Update news and software releases in notes
- [ ] Update job listings
- [ ] Update introduction question
- [ ] Mail out 3 day before meetup reminder
- [ ] Update meetup.com
- [ ] Check-in with speakers 3 days prior to meetup
- [ ] Tweet out 3 day before meetup link
- [ ] Tweet out 1 day before meetup link
- [ ] Tweet day of meetup link

## See also

- [Exchange.js Speakers](https://docs.google.com/spreadsheets/d/1_FOG1K_fUbTlNvqT9hjihiXYt9AhPkZxW6tfZN858VU/edit?usp=sharing)
- [Preroll Slides](https://exchangejs.github.io/exchangejs-preroll)
- [Meetup slides](https://docs.google.com/presentation/d/1DH0pD5km1YVCrMRqdTt9AHbgQW84FNZqxj9mcjmCJA0/edit#slide=id.p)

/cc @ExchangeJS/organizers

**Comment by MarkBennett** [comment]
@snostorm setup an issue to keep track of this months meetup ;)

**Comment by MarkBennett** [comment]
@dlolsen thoughts on food this month? Remedy did a pretty solid job last year for around $200.

**Comment by MarkBennett** [comment]
I'm going to make a quick pass at the notes today @snostorm, but feel free to edit them as you see fit. 

Also, what do you think about dropping the sponsor messages this month and just saying thanks instead? I'll confirm with Jobber and Investopedia but am pretty sure they'd be ok with it until we can come up with something that isn't quite so stiff.

**Comment by dlolsen** [comment]
@MarkBennett I'll get on the horn with them! Oct. snuck up on me!

**Comment by dlolsen** [comment]
@MarkBennett Remedy can do wraps. Did you guys get them halved (or less) last time?

**Comment by benzittlau** [comment]
@MarkBennett I'm fine with that change to the sponsorship section.

**Comment by MarkBennett** [comment]
@dlolsen yes, that seemed to work out pretty well thanks!

**Comment by MarkBennett** [comment]
@benzittlau Thanks. Still partial to the idea of some kind of message but what we had felt awkward, especially with @snostorm MCing this month.
