### ISSUE TITLE
Speaker Calendar 2018-19

### ISSUE THREAD

**Issue by CAYdenberg** [ExchangeJS/exchangejs.github.io#105]
https://docs.google.com/spreadsheets/d/1cJBKmuUc88IZqc6e7axIDA8Wq-UwmF15nfYWXffymZU/edit#gid=156190243

@MarkBennett any exciting insight from the June survey? Any talk inspiration ideas?

/cc @ExchangeJS/organizers

**Comment by MarkBennett** [comment]
Here's the results of the survey @CAYdenberg:

https://docs.google.com/forms/d/1YzjG7-NUchvuccESG5RhUVa24oUKDiojjcSNR12jMb4/edit#responses

Some of the stand out ideas for talks include:

1) More demos of app and frameworks
2) Framework intros
3) TypeScript
4) Fishbowl discussions
5) react/vue talks
6) Explore other programming languages
7) Languages which compile to JS
8) Unconference night
9) Accesability in SPA
10) SVG basics
11) Building P2P apps

**Comment by CAYdenberg** [comment]
@ryanramage any interest in giving a talk on P2P apps (possibly using dat/beaker)?

**Comment by MarkBennett** [comment]
Hey @CAYdenberg, @ryanramage and I are signed up to do a pair of talks on DAT in September. As I understand it, his is an introduction to the protocol itself, whereas I'll demo using DAT via Beaker and the CLI. In future talks I'll build out a version of https://devdoc.io running on DAT.
