### ISSUE TITLE
Update Meetup Page with new meetings for the Fall

### ISSUE THREAD

**Issue by abramhindle** [ExchangeJS/exchangejs.github.io#107]
The September meetings are not listed on the webpage. Or any of the Fall meetings.

**Comment by MarkBennett** [comment]
@abramhindle the next event is listed on meetup.com at:

https://www.meetup.com/startupedmonton/events/253997418/

Let's just drop the list of meetups from the website and ask people to visit meetup.com for details and to RSVP. I'll update the September meetup with details on the talks so we can start advertising.

**Comment by MarkBennett** [comment]
I've dropped the list of past meetups and linked to meetup.com. Closing.
