### ISSUE TITLE
September 2018 Meetup

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#108]
## To Do
- [X] Arrange MC (Sean Ouiment)
- [x] Arrange food NHON HOA SANDWICH BAR delivered via Skip 6pm - 6:30pm
- [X] Arrange meetup recording (Mark)
- [ ] ~Do pre-interview with speakers 2 weeks prior to meetup~
- [ ] Review and tweak preroll slides
- [x] Create notes [see notes](https://docs.google.com/presentation/d/18qbkttjprQ1mp7bk1nPe2vekHD3f8Jm4yYKyuIw06ZM/edit?usp=sharing)
- [x] Update speakers in notes
- [x] Update events in notes
- [x] Update next meetup in notes
- [ ] Update news and software releases in notes
- [x] Update job listings (generic now, no?)
- [x] Update introduction question
- [ ] Mail out 3 day before meetup reminder
- [ ] Update meetup.com
- [x] Check-in with speakers 3 days prior to meetup (confirmed otherwise)
- [ ] Tweet out 3 day before meetup link
- [ ] Tweet out 1 day before meetup link
- [ ] Tweet day of meetup link

## See also

- [Meetup.com RSVP](https://www.meetup.com/startupedmonton/events/tzwddqyxmbjb/)
- [Exchange.js Speakers](https://docs.google.com/spreadsheets/d/1_FOG1K_fUbTlNvqT9hjihiXYt9AhPkZxW6tfZN858VU/edit?usp=sharing)
- [Preroll Slides](https://exchangejs.github.io/exchangejs-preroll)
- Meetup slides (ADD A LINK!)
- [Past talks](https://drive.google.com/open?id=0B1angknldByTSUx0eFJsN0VOcjQ)

/cc @ExchangeJS/organizers

**Comment by MarkBennett** [comment]
@seanhealy is organizing some stuff for hactoberfest. No specifics yet but I've asked him to let us know what if anything we can announce.

Dev Edmonton is also organizing an unconference style event for November as a sort of coming out party. Details to follow but I'm hoping to have a landing page up for people to sign up to for info and that we can share on Thursday night.

I haven't heard from Ryan Ramage in the last few days but I'll follow up on his DAT talk and my demo. It would be great if we could get an intro style React or JS Basics talk. I'd do it myself but I don't want to be the one talking the whole time. ;)

**Comment by abramhindle** [comment]
I'll MC

**Comment by MarkBennett** [comment]
> I'll MC

I think @snostorm is gong to MC this month @abramhindle.

Can you confirm Sean?

**Comment by CAYdenberg** [comment]
You're looking for a react basics talk for **this week**? I think I could throw something together

**Comment by MarkBennett** [comment]
> You're looking for a react basics talk for this week? I think I could throw something together

We are. That would be great if you think it's achievable. Thoughts @snostorm?

**Comment by snostorm** [comment]
> We are. That would be great if you think it's achievable. Thoughts @snostorm?

I'd be cool with an extra talk @CAYdenberg! Still enough time to put it together before tomorrow?

> I'll MC

@abramhindle I am cool to trade off or get an assist on the MC'ing efforts tomorrow  – although it might be easiest to start in October. Part of my homework tonight is getting the slides/news/etc. together so that typically pairs up well with MC'ing. But if you want to email/Twitter DM me we can coordinate a logical split up of the MC'ing for September even – for example, if you wanted to take on the second half: introducing speakers, facilitating a discussion, thank you's, etc. I could cover intro's and news. But I am open to ideas.

**Comment by snostorm** [comment]
@MarkBennett et. all based on the feedback from the membership survey I'd vote either: no discussion tomorrow _or_ we skip recording it. I feel trying to use the microphones for this session makes this too formal and probably a few people shy.

**Comment by abramhindle** [comment]
@snostorm Hi, go ahead and MC. I was just trying to be helpful :)

**Comment by CAYdenberg** [comment]
I'm on it! The title will be "Why and how to start with React"

**Comment by ryanramage** [comment]
Is there a slide deck that I can edit my pic/profile and company info?

**Comment by MarkBennett** [comment]
> all based on the feedback from the membership survey I'd vote either: no discussion tomorrow or we skip recording it. I feel trying to use the microphones for this session makes this too formal and probably a few people shy.

@snostorm Why don't we skip recording then vote at the meetup on if people want a discussion?

**Comment by MarkBennett** [comment]
> Is there a slide deck that I can edit my pic/profile and company info?

@snostorm can you help @ryanramage with this?

**Comment by MarkBennett** [comment]
@snostorm BTW if you or anyone else is looking for the A/V equipment from Startup Edmonton I've swiped it and have it here at my house so I can work on getting it setup in advance.

**Comment by snostorm** [comment]
@ryanramage I already have it somewhat prepared (no employer info but can sneak it in) ... for this season's deck I am trying to use "photos from the past" (as much as possible) but I am open to swapping it. I assume you mean the general meetup deck and not the shared deck with @MarkBennett for the DAT talk?

https://docs.google.com/presentation/d/18qbkttjprQ1mp7bk1nPe2vekHD3f8Jm4yYKyuIw06ZM/edit?usp=sharing

**Comment by ryanramage** [comment]
@snostorm , I looked at the deck and it looks great. I will leave it as is.

**Comment by MarkBennett** [comment]
@snostorm New slide deck looks AWESOME. Nice work! 🎉

**Comment by MarkBennett** [comment]
Thanks to @snostorm for an awesome meetup this month!

Closing this issue.
