### ISSUE TITLE
Pull meetup details from Github or Meetup.com

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#16]
Looking for ways to update website without manually needing to change index.html

**Comment by MarkBennett** [comment]
Let's do this @seanhealy! :)

**Comment by cwant** [comment]
Continuing the discussion from the issue in the other repo [1], here is an expanded demo with some fault tolerance built in:

https://jsfiddle.net/cwant/x6xsbuz0/15/

(Still not production-ready, but closer.)

Chris

[1] https://github.com/ExchangeJS/exchangejs.com/issues/3
