### ISSUE TITLE
Member survey

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#19]
So that we can understand who are members are, and how we can best serve the local community, we need to send out a short member survey that we can share at the March 3rd meetup.
- [x] draft survey
- [x] send out survey for review
- [x] finalize survey
- [x] share survey with members
- [x] close survey and compile results

**Comment by MarkBennett** [comment]
Via @abramhindle in last nights planning meeting:

> Jeff if you want google survey help/suggestions talk to Abram’s student [Candy Pang cspang@ualberta.ca](mailto:cspang@ualberta.ca) who has [survey experience](https://peerj.com/preprints/886/).

**Comment by MarkBennett** [comment]
Here are some ideas for questions..
- how long have you been coming to the meetup?
- how would you describe your JavaScript skill level: beginner, intermediate, or advanced?
- have you been looking for work or new contracts in the past year?
- why do you come to the meetup?
- what works well at the meetup now?
- what should we do more of at future events?
- what isn't working for you with the meetup?
- would you consider volunteering to give talks, organise events, or other support?
- would you consider being a member of the exec?
- what technologies would you like us to explore in the next year?
- what are other events or meetups you think we should take inspiration from?
- would serving alcohol during the meetup make you more or less likely to attend?

That's all I can think of for now!

**Comment by abramhindle** [comment]
This was discussed during the exec meeting, Jeff have you made any progress on this?

**Comment by MarkBennett** [comment]
I'm going to draft a copy of this survey so everyone has time to give feedback before we share it with members at the next meetup.

**Comment by MarkBennett** [comment]
Ok. I've got a draft up. Feedback welcome:

https://docs.google.com/forms/d/1xHHaW64uVKBm0UYo_yctQnwoQYCqdvVtVASYHHz7lS4/edit

**Comment by MarkBennett** [comment]
I've just closed the survey. We had 27 responses with lots of great feedback. I'm working on summarizing the results, but you can see the raw data at:

https://docs.google.com/forms/d/1xHHaW64uVKBm0UYo_yctQnwoQYCqdvVtVASYHHz7lS4/edit#responses

**Comment by MarkBennett** [comment]
Summarizing didn't take as long as I thought, here's the link!

https://docs.google.com/document/d/1QFR-3w-D8Wl5MlEfPnpBfqAyvXjlN7NzucMtznvFCe8/edit?usp=sharing
