### ISSUE TITLE
Create a sponsorship package

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#20]
Deliver a one-page PDF we can send to sponsors. It should describe:

1) What the meetup is
2) Our mission
3) Who our members are
4) What we're going to do with the money
5) What you get for sponsoring
6) Our sponsorship levels
7) How to donate

**Comment by MarkBennett** [comment]
I setup a slidedeck that we can give to sponsors. Right now anyone can use this link to edit, so go crazy. If you can sign in with a Google account so we can track who's doing what that would be great.

https://docs.google.com/presentation/d/12_2aRmpxVoZZcnujocWaQICOYgk_t9a0AXaAnf64OSw/edit?usp=sharing

**Comment by MarkBennett** [comment]
@MHerszak here's the sponsorship package as it stands now. I still need to spend a few more hours to integrate the results of the sponsor survey and better articulate our mission. It's also _way_ to long right now so I'm going to cut down and focus the content.

You can leave suggestions and ideas here, or just leave comments right in the slidedeck too.

**Comment by MHerszak** [comment]
I just looked at the slide deck. I would assume you could put all of it in max 5 slides. The most important parts are to actually show what the sponsor accomplished with his donation. It is just a side effect that we profit from this, too. What do you think?

**Comment by MarkBennett** [comment]
It will definitely be less than what's there now. Hard to say an exact number for sure but that's in the range. This was from a template so there's a lot that's not needed.

The whole point is to convince people to donate, so I think we will need to explain what we'll do with the money so they can feel we'll be accountable for it but the main focus should be on getting the sponsors to send money our way which means we'll focus mostly on the benefits they'll get from sponsorship.

**Comment by MarkBennett** [comment]
Alright everyone, slidedeck is done and ready to go. You can download a copy [here](https://github.com/ExchangeJS/exchangejs.github.io/files/460272/Sponsorship.Package.2017.pdf) or [view the slides online](https://docs.google.com/presentation/d/12_2aRmpxVoZZcnujocWaQICOYgk_t9a0AXaAnf64OSw/edit?usp=sharing).

Up next we need to start making a list and contacting potential sponsors. See #59.
