### ISSUE TITLE
Setup global repo for all monthly meetups

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#23]
We decided to setup a single repository we can use for all monthly meetups. This repository will include:

1) Slides for all meetup notes
2) An issue for each meetup

The pro's of doing this are that we can eliminate the duplication of work and resources between months, and use an issue template to help with planning them. It also means that there is only one repository you need to check out to access all past talks. The con's of doing this are that it's possible older slides might stop working if some of their dependencies are changed without archiving older versions of the CSS and JS. I think we can all live with this though.

**Comment by MarkBennett** [comment]
Question, do we want to put this into the same repo as [the exchangejs.com website](https://github.com/ExchangeJS/exchangejs.github.io), or into a secondary repository just for meetup planning?

My vote is to split them. This lets us treat the main website as a single app. The code it uses is very different from those for the monthly slides, and then we can separate our meetup planning from maintaining and enhancing exchangejs.com.

Based off the discussion last night, it sounds like everyone was in favour of a single repo for all the meetup notes and planning. Unless I hear otherwise in the next few days, that's what I'll go ahead and do.

/cc @seanhealy, @abramhindle, @JeffMarvin

**Comment by MarkBennett** [comment]
Hey guys, I haven't heard back from anyone on this. I'm going to go ahead and make the new repo the will contain all notes going forward.

**Comment by seanhealy** [comment]
I would prefer to put them in the same one I think…

**Comment by MarkBennett** [comment]
@seanhealy can you elaborate? Do you mean notes, website, issues?

**Comment by MarkBennett** [comment]
Ok. We've already agreed on setting up a single repo for the notes. I'll go ahead and do that and we can decide where the issues go later once others have a chance to weigh in. We can have the discussion of where issues go in #25.

**Comment by MarkBennett** [comment]
Done.
