### ISSUE TITLE
Record talks

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#28]
Starting September 2016 we'd like to record our meetups for broadcast to our members live and offline later.

**Comment by MarkBennett** [comment]
I was watching a talk on the new Servo Webrenderer and noticed that Mozilla publishes the source for http://air.mozilla.com. It looks like this might include a nice setup for their video streams with shots of the speaker and their machine.

https://github.com/mozilla/airmozilla

I'll dig through it and see what I can find.

**Comment by MarkBennett** [comment]
It's super rough, but I was able to stream a nice quality video to Youtube Live using the open source OBS project. Note I used the laptop microphone for this but have a studio quality external USB microphone we could use at the meetup. I'll upload another sample with that later. I've also used the Youtube tools to edit out the first 7 minutes of me messing around with the recording. It's still processing but I'm hoping this doesn't hit the quality too much.

https://www.youtube.com/watch?v=0ZhCd6qP8Po

On the plus side, it lets us do lots of nice branding and has a video feed that doesn't overlap the screen. On the negative side, our presenters would need to all present from a single laptop, or we'd need to get an HDMI capture device. This might not be a big deal though.

/cc @seanhealy @abramhindle

**Comment by MarkBennett** [comment]
Here's a take with external microphone and transitions.

https://www.youtube.com/watch?v=QwBvPgf0TKU&feature=youtu.be

**Comment by MHerszak** [comment]
@MarkBennett what would you suggest as a microphone? Links?

**Comment by MarkBennett** [comment]
I've used the Yeti USB and it works well enough, but picks up a lot of keyboard noise when it's on the same surface as the presenters laptop. It's quite large and heavy, so I haven't been able to find a microphone stand which will support it, but perhaps placing on a padded stand of some sort would be a place to start? Otherwise, maybe we could find a cheap clip on microphone?

http://www.bluemic.com/products/yeti/

**Comment by MarkBennett** [comment]
The Calgary meetup uses something like this:

https://www.amazon.ca/Yamaha-AG03-Mixer/dp/B00TY8JE60/ref=pd_sbs_267_7?ie=UTF8&dpID=51qiJqYFAmL&dpSrc=sims&preST=_AC_UL160_SR160%2C160_&psc=1&refRID=29E47XP901PV2DKR2KK3

To mix audio from various microphones and laptops so that they can stream with clear audio.

**Comment by MHerszak** [comment]
The Yeti USB (http://www.bluemic.com/products/yeti/) has two different pattern in order to avoid noise and to enhance audio input. Did you select a specific pattern (BIDIRECTIONAL, or CARDIOID MODE)? The other pattern will pick up sound from anywhere.

**Comment by MarkBennett** [comment]
I've played with both and found it still gets keyboard noise, though you're right that it does make a difference. I'm thinking a [lapel microphone (lavalier)](https://www.amazon.ca/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=Lavalier+Microphone) would make a lot of sense for what we're trying to do at the meetup since we could use it to just grab the speaker. We could then combine it with the Yeti to pickup questions out on the floor.

**Comment by MHerszak** [comment]
One question. StartUp has nothing we can borrow?

**Comment by MarkBennett** [comment]
They have a hand held microphone that we could try, but I've found a lot of speakers don't like using it. Perhaps that will be different if we're recording. They're not setup to do screencasting, but I've been wondering if we could split the costs with them or come up with some other arrangement once we know what we need.

**Comment by MHerszak** [comment]
That is what I would suggest, too. Because who is going to take care of the equipment once we have it and why should it be locked away for a whole month if someone else could rent it. Having said this, who is going to be responsible in case it breaks or who will have the key and the overlook when someone is going to rent it?

**Comment by MarkBennett** [comment]
Ideally, I'd like to have a place at StartupEdmonton where we could leave the equipment so we wouldn't need to rely on one member of the exec being there every month. Like you said, perhaps other meetups could use it as well if we can come up with a reasonable agreement with StartupEdmonton. I'd mostly be concerned about having access when we need it, and who would be responsible when it breaks.

Why don't I approach Warren from StartupEdmonton and see what there taking on recording talks is?

**Comment by MHerszak** [comment]
I can do that.

**Comment by MarkBennett** [comment]
@mherzak Not sure I follow. Do what?

**Comment by MarkBennett** [comment]
Are you talking about emailing Warren? If so I've already done that. I'll update here as soon as I hear back but it might take him a few days to get back.

**Comment by seanhealy** [comment]
@MarkBennett You can also get some mics that have a ring that they use to suspend the actual mic from the stand. I wonder if that would help to reduce keyboard noise…?

**Comment by MarkBennett** [comment]
@seanhealy do you have an example? Curious about price.

**Comment by MHerszak** [comment]
@MarkBennett I am at StartUp a lot and I can just talk to him. A quick talk is a bit more effective than email. Let me know if you hear back. If not I can talk to him.

**Comment by MarkBennett** [comment]
Sounds good @MHerszak. I haven't heard anything from Warren yet. Lets give him a few more days and if we haven't heard from him by Monday, maybe you can approach him next week. It would be great if we could convince StartupEdmonton to setup and maintain what we need to screencast as I'm sure there are lots of other meetups and events that would use it. ;)

**Comment by MarkBennett** [comment]
I haven't heard back from Warren at StartupEdmonton. If you see him around, can you ask him for his thoughts on this @MHerszak? I was also thinking it would make sense for us to reach out directly to some of the other meetups to get a sense of who else might be interested. The Python and Go meetups come to mind, perhaps the Ruby one (though I hear it's not as active as in the past?)

**Comment by MHerszak** [comment]
Let's talk to Warren first. I can go there tomorrow.

**Comment by MarkBennett** [comment]
Sounds good. Thanks @mherszak!

**Comment by MarkBennett** [comment]
Thanks for stopping by @mherszak. That seems to have gotten a reply, though not the one we may have wanted. Looks like we're on our own for costs, but perhaps we can convince them on a safe place to store?

His reply follows:

> Hi Mark,
> 
> Sorry for the delay on this - looks like there was a little miscommunication around who was going to get back to you.
> 
> Michel just stopped by to chat about the sound in the Program Room as well!
> 
> We have recorded talks in the space in the past and it's definitely something that I think there would be value in doing and sharing with a larger audience. 
> 
> It's not something we're in a position to support in the way of purchasing equipment but we would be happy to provide the opportunity to post the videos on our Startup Edmonton youtube channel and provide you with a sample photo release that you can use to acquire consent from speakers/attendees who may be pictured in the videos.
> 
> In terms of sound, there is a microphone available underneath the podium in the Program Room. If you're interested in alternative microphones (wireless, lapel, etc.) your best bet would be to rent from Long & McWade (they have very affordable rates!).
> 
> Let me know what your plan is moving forward. I'm happy to support this in any way that we can and to help solve any issues you may be having with sound during your events.
> 
> Hope this helps!
> 
> Warren

**Comment by MHerszak** [comment]
It is something. I don't mind renting if what Startup has isn't enough otherwise we need a dedicated equipment person. That person needs to make sure the purchased electronics are at every meeting. Having said this, if we decide to rent someone has to pick it up and bring it back, too. I am not sure about the better solution. @MarkBennett have you tested their mixer/panel and their mic? I haven't seen it, yet.

**Comment by MarkBennett** [comment]
@MHerszak I don't have one no, but the Calgary meetup has used it along with Google Hangouts with a lot of success. The reviews on Amazon are also good, so I'm confident it could do what we need.

I spoke with Warren again and Startup Edmonton is willing to give us a private locker, so we'll have a place to store whatever equipment we get. I'm just checking to see if it will need a key, or if we can use a combo lock and just share the code. It would ideal if there was flexibility about who has access since I usually, but not always, am at the meetups so having multiple people with access is important.

I'm thinking without Startup putting up funds, we should focus on the audio and get the mixer then use Google Hangouts to do the screen capture, streaming, and archiving to Youtube. We can still pitch getting an HDMI pass through adapter to the sponsors as you never know what they'll chip in for, but I think getting good audio is the most important. We can also easily add this later, but this would be enough to get us setup for recording this September.

Thoughts?

**Comment by MHerszak** [comment]
Hangout is good! This way we can also invite other speakers without them having to travel. And that could be FeatherJS :)

**Comment by MarkBennett** [comment]
I setup a channel for us on Youtube:

https://www.youtube.com/channel/UCBC21Bfijpx4CCpjnBUdypg

still trying to figure out how to get a better url. Apparently, it's linked to a G+ page which I can invite other users to. This will supposedly allow any of us to post to this channel, though I haven't tested that.

**Comment by MarkBennett** [comment]
Today was a big sale on amazon.ca I got a sweet Logitech HD webcam with tripod for 40% off and 60% off a boom microphone with screen that we can attach to the position. I'm hoping this will significantly increase the quality of our recordings. Thanks to @seanhealy for the heads up.

**Comment by MarkBennett** [comment]
![img_20160714_171722](https://cloud.githubusercontent.com/assets/61872/16858832/107fd342-49e7-11e6-9164-854a1b2c6557.jpg)

Camera and tripod arrived today. Boom microphone should be here tomorrow.

**Comment by MarkBennett** [comment]
The microphone just arrived. Here's a test of the HD video and recording with the new microphone.

https://www.youtube.com/watch?v=XD5xTdUfNds

**Comment by MarkBennett** [comment]
We've been recording for a few months now and feedback has been good. Looking forward to upgrading talks once we can afford some more equipment but I'm satisfied this is done for now. We can make a new issue once we're ready to upgrade.
