### ISSUE TITLE
Adopt a Code Of Conduct

### ISSUE THREAD

**Issue by ryanramage** [ExchangeJS/exchangejs.github.io#3]
In person communities always benefit from a code of conduct, to encourage good behaviour and diversity. I propose to adopt this:

http://confcodeofconduct.com/

And just rename 'conference' to  'exchangejs' . We can then link to it each meetup.

**Comment by MarkBennett** [comment]
Great idea @ryanramage. This looks like as good a starting place as any for a code of conduct.

@seanhealy @abramhindle @JeffMarvin any thoughts?

**Comment by MarkBennett** [comment]
The Code of Conduct is live on our site now:

http://www.exchangejs.com/code-of-conduct.html

Closing this issue.

**Comment by ryanramage** [comment]
awesome, thanks!
