### ISSUE TITLE
Talk to Sean O. about getting an email address at @exchangejs.com

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#30]
It sounds like Twitter will want to see email from xyz@exchangejs.com to get our twitter handle. @snostorm runs the domain and would therefore need to set this up.

**Comment by MarkBennett** [comment]
@snostorm would this be hard to setup? Alternatively, if you want to transfer the domain to someone else we can set this up pretty quickly too. Thanks!

**Comment by MarkBennett** [comment]
Haven't heard anything from Sean yet. I tried him on Facebook this morning but I think we'll need to consider this blocked.

Does anyone else know a good way to reach him?

**Comment by MarkBennett** [comment]
I'm meeting Sean for lunch on Thursday to catch up and will mention this to him then.

**Comment by MarkBennett** [comment]
I spoke with Sean when we met for lunch and he's looking into this. He's going to try to join us at our planning meeting Thursday night.

**Comment by snostorm** [comment]
Been looking in to this again. No hosting setup at this time. We're exploring options. One option is to alias somebody else who has a Google App account right now. Alternative is to find a free hosted domain email provider.

Edit: MX points at Google, but no actual account setup

**Comment by MarkBennett** [comment]
Thanks for looking into this @snostorm. If we can even set this up somewhere temporarily and just use it to verify our email with Twitter, then that should be enough to start claiming the account.

**Comment by MarkBennett** [comment]
Want to take a look into this with me at the next hackup? Would be nice to get this sorted out.
