### ISSUE TITLE
March 2016 Meetup

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#31]
Arrange and present the meetup.
## To Do
- [x] Find a sponsor
- [X] Arrange MC (Mark)
- [x] Arrange food
- [x] Update speakers in notes
- [X] Update events in notes
- [X] Update next meetup in notes
- [X] Update news and software releases in notes
- [X] Update job listings
- [x] Update introduction question
- [x] Update sponsor thank you
- [x] Mention exec and volunteer selection at June meetup

/cc @ExchangeJS/organizers

**Comment by MarkBennett** [comment]
I'm thinking we use this issue to plan this months meetup, then it can become the basis for a template we can use in the future.

**Comment by MarkBennett** [comment]
Need to mention upcoming exec selection and summer planning and volunteer opportunities.

**Comment by MarkBennett** [comment]
@abramhindle if you let me know the title of your talk I can add it to the notes. Thanks!

**Comment by MarkBennett** [comment]
I've created #33 with a PR for the new notes. Still a few things to update but feel free to make edits on the branch and after it's merged into master.

**Comment by abramhindle** [comment]
Introduction to Scope & Functions in Javascript

**Comment by MarkBennett** [comment]
Thanks @abramhindle. Added!

**Comment by MarkBennett** [comment]
All the speakers and notes are done, except for figuring out the sponsor. I believe Jobber sponsored last month. @seanhealy do you think Clio would be willing again?

**Comment by seanhealy** [comment]
@MarkBennett Clio is in for sure! We're also looking hard for a Sr. JS dev so, this lines up nicely. :)

**Comment by MarkBennett** [comment]
Thanks @seanhealy! I'll update notes and merge later today. Just need to add news about upcoming exec selection.

**Comment by MarkBennett** [comment]
@abramhindle How does this slide look to introduce your talk. Might still tweak CSS but are contents and links good?

https://www.exchangejs.com/events/mar-2016/#/7/1

**Comment by MarkBennett** [comment]
I'm merged the pull request. You can now edit the notes for Thursday's meetup at:

https://github.com/ExchangeJS/exchangejs.github.io/blob/master/events/mar-2016/index.html

**Comment by MarkBennett** [comment]
@seanhealy are you able to take care of the food for this meetup?

**Comment by seanhealy** [comment]
@MarkBennett Already ordered! :)

**Comment by MarkBennett** [comment]
Meeting done
