### ISSUE TITLE
April 2016 Meetup

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#35]
Arrange and present the meetup.
## To Do
- [ ] Find a sponsor
- [x] Arrange MC (Mark)
- [ ] Arrange food (Sean)
- [x] Update speakers in notes
- [x] Update events in notes
- [x] Update next meetup in notes
- [x] Update news and software releases in notes
- [ ] Update job listings
- [x] Update introduction question
- [ ] Update sponsor thank you
- [x] Mention exec and volunteer selection at June meetup
- [x] Share member survey #19 
- [x] Share sponsor survey  #36
- [x] Thank Jeff for his hard work

/cc @ExchangeJS/organizers

**Comment by MarkBennett** [comment]
I've found a couple of speakers for this month's meetup.

1) @m.herszak is going to speak about Ionic 2
2) @_eddieantonio is doing an introduction to prototypical inheritance

I've also got a lead on one more talk, but am still trying to track them down to confirm.

**Comment by MarkBennett** [comment]
I've got a placeholder for the notes up.

https://github.com/ExchangeJS/exchangejs.github.io/blob/master/events/apr-2016/index.html

Will update over the next few days.

**Comment by seanhealy** [comment]
I'll get food dealt with again. :)

**Comment by MarkBennett** [comment]
So the notes are basically done. The only things missing are:

1) A sponsor for this month
2) Confirmation for the job postings

**Comment by MarkBennett** [comment]
Link to live notes.. https://www.exchangejs.com/events/apr-2016/#/
