### ISSUE TITLE
Create a survey to understand sponsors

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#36]
If we're going to attract sponsors we need to know who they are, what they want, and amount and type of support they can provide.

This doesn't need to be fancy, but it would be useful to have results by the start of July so we can plan over the summer.

**Comment by MarkBennett** [comment]
I've created a draft of the survey you can check out here. You should all be able to edit it, but it with your Google account but if for some reason you can't just let me know.

https://docs.google.com/forms/d/136u-YT5FeRzaG_o5FB5Iv1c6ylb8soDmWRlqcOCTt9M/edit?uiv=1

**Comment by MarkBennett** [comment]
@ExchangeJS/organizers can you all take a few minutes to send a link to this survey out to anyone you know that would be interested in sponsoring the meetup next year? I'm working on the sponsorship pitch and budget right now and getting a few more answers to this would be awesome!

Here's the link so you've got it handy!

http://goo.gl/forms/NOxdiwOHHn7dv5uM2

**Comment by MHerszak** [comment]
We could have a list and we name one person to do this. I fear we'll be sending emails to the same sponsors and spam them. Just a thought.

**Comment by MarkBennett** [comment]
Good point @mherszak. If people post names and emails in this thread I can send emails to anyone that hasn't already been contacted.

**Comment by MarkBennett** [comment]
We've gotten a few responses, which is realistic given the number of potential sponsors in Edmonton. I think we've got enough of a background to move forward with approaching people.

I'm going to close this issue and end new responses to the survey.

**Comment by MHerszak** [comment]
Who did you end up asking?

**Comment by MarkBennett** [comment]
I heard from Jobber and a few other people. I've got enough to put together the rest of the pitch. We need to start going after sponsors now if we want to have a budget in place for September.

**Comment by MHerszak** [comment]
Do we have a number for a budget? It is easier to ask for money when you know what to ask for. I can help with the asking part. UPDATE @MarkBennett nvm.. I forgot about your list on Google Drive. I'll check that again. Btw, is there a way we could share our thoughts on the pitch slide deck?

**Comment by MarkBennett** [comment]
@MHerszak here's the proposed budget

**Comment by seanhealy** [comment]
@MarkBennett Did you miss an attachment or link? :)

**Comment by MarkBennett** [comment]
Ha ha, yup. Wrong issue @MHerszak @seanhealy. The right one is #44.
