### ISSUE TITLE
May 2016 Meetup

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#38]
Arrange and present the meetup.
## To Do
- [x] Find a sponsor (Jobber)
- [x] Arrange MC (Mark)
- [x] Arrange food (Ben from Jobber)
- [x] Update speakers in notes
- [x] Update events in notes
- [x] Update next meetup in notes
- [x] Update news and software releases in notes
- [x] Update job listings
- [x] Update introduction question
- [x] Update sponsor thank you
- [x] Mention exec and volunteer selection at June meetup
- [x] Share member survey #19 
- [x] Share sponsor survey  #36

/cc @ExchangeJS/organizers

**Comment by MarkBennett** [comment]
@ExchangeJS/organizers I'm thinking of doing something different this month and doing a mini democamp of sorts where people get 5-10 minutes to show off something cool they've built with JavaScript. It doesn't need to be production, but it should only be code and demo, no slides or notes.

Thoughts? I'm going to send out a message to members to see what the level of interest is.

**Comment by abramhindle** [comment]
That's a good idea. Do we have enough people on the list for this work? We probably want 6 or more.

**Comment by MarkBennett** [comment]
I have one demo lined up but am going to start spamming everyone I know to get more. Would any of your students have something to show?

**Comment by MarkBennett** [comment]
Ok, just sent out a handful of emails. Will update this issue again when I hear back.

**Comment by MarkBennett** [comment]
@seanhealy won't be at Thursday's meetup but mentioned Jobber is sponsoring and @benzittlau will be taking care of the food.

**Comment by MarkBennett** [comment]
Draft of notes is checked in:

https://github.com/ExchangeJS/exchangejs.github.io/blob/master/events/may-2016/index.html
