### ISSUE TITLE
June 2016 Meetup

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#39]
Arrange and present the meetup.
## To Do
- [x] Find a sponsor (Clio)
- [x] Arrange MC (Mark)
- [x] Arrange food (Sean)
- [x] Update speakers in notes
- [x] Update events in notes
- [x] Update next meetup in notes
- [x] Update news and software releases in notes
- [x] Update job listings
- [x] Update introduction question
- [x] Update sponsor thank you
- [x] Run exec and volunteer selection at June meetup
- [x] Share member survey #19 
- [x] Share sponsor survey  #36

/cc @ExchangeJS/organizers 

[view notes](https://www.exchangejs.com/events/jun-2016/) / [edit notes](https://github.com/ExchangeJS/exchangejs.github.io/blob/master/events/jun-2016/index.html)

**Comment by MarkBennett** [comment]
Karim Baaba mentioned at the May meetup that he was interested in talking about generators. Sean H. could talk about ng-conf, and Sean O. could talk about web components. Need to follow up.

**Comment by MarkBennett** [comment]
I just spoke with Karim and he's out for this month, though would still like to talk when we come back from the break in September.

**Comment by MarkBennett** [comment]
@seanhealy any interest in talking about ng-conf at all?

@snostorm still interested in talking about web components?

**Comment by MarkBennett** [comment]
We need to decide how to select exec for next year. I'm thinking we just take interested parties, then if we get more than 5 we do a random selection instead? My feeling is we probably won't make it that far. Agreed?

**Comment by abramhindle** [comment]
I think we're probably OK for now. 

I will not be in attendance that evening, I apologize.

**Comment by MarkBennett** [comment]
Thanks @abramhindle!

**Comment by MarkBennett** [comment]
@seanhealy any leads on a food sponsor this month?

**Comment by MarkBennett** [comment]
@abramhindle are you interested in remaining on the exec? I'm just making my list for tomorrow.

**Comment by MarkBennett** [comment]
Meetings done. Closing.
