### ISSUE TITLE
Archive old repos

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#40]
This will make it easier for new contributors to know where to go.

**Comment by MarkBennett** [comment]
I've looked into doing this, and [GitHub doesn't support archiving repos](https://help.github.com/articles/can-i-archive-a-repository/).

Instead they suggest doing a fetch and then deleting the GitHub repo. I've already got all the talks going back to since I took over on my laptop. I can zip these up into an archive and post it online. Anyone have a problem with me deleting the old repos?

/cc @ExchangeJS/organizers

**Comment by seanhealy** [comment]
I've no issue with this. Think simplifying these would be nice.

**Comment by MarkBennett** [comment]
Alright. I'll go ahead and erase the old repos.

**Comment by MarkBennett** [comment]
Done.

**Comment by MarkBennett** [comment]
Archive of old repos https://storage.googleapis.com/sandbox-180/exchangejs.tgz
