### ISSUE TITLE
ExchangeJS Conference in Edmonton

### ISSUE THREAD

**Issue by MHerszak** [ExchangeJS/exchangejs.github.io#41]
I would like to organise a conference for Javascript related topics. I would aim for either May or September. Has anyone ever done that and what would you actually want one in Edmonton?
- [ ] Team up with StartUp Edmonton to help with the orga
- [ ] We could use the ExchangeJS page for Conference details and Eventbrite to sell tickets.
- [ ] Shaw Conference center as venue
- [ ] Call for proposals
- [ ] Catering
- [ ] Flyer, Poster, Online advertisment

What do you guys think?

**Comment by MarkBennett** [comment]
@seanhealy I know you've organised conferences at larger venues before. Any thoughts on how we'd get this done? Do you know what we'd need to do to work with a larger venue to Shaw?

**Comment by seanhealy** [comment]
When we did polyglot one of our organizers down there actually hooked us up for some fantastic space that was actually free. I've never worked with the Shaw before but, my GF's brother actually works there on all their IT setup so I can inquire with him if you would like…

How many attendees were you thinking of?

Also, as a heads up I'm looking to get this years Polyglot setup to happen this fall if you would be interested in helping it could be some good experience for something like this as well.

**Comment by MarkBennett** [comment]
Interesting. I think we need to decide on our priorities for the next year. This could be a valuable addition to the community but could also take away manpower from things like getting sponsorships and trying to bring in higher profile speakers for the meetup. On the flip side, a good conference would do a lot to increase the credibility of the Edmonton JavaScript community. Do we know what the interest level would be, and how much of a financial commitment it would be up front? Those would be important in deciding if this is feasible.

**Comment by seanhealy** [comment]
Another option would be do just to get a stronger JS presence at Polyglot… Donno… :)

**Comment by seanhealy** [comment]
I do see your point about spreading ourselves too thin…

**Comment by MarkBennett** [comment]
I don't want to sound to negative on this idea. It's something we've talked about for a while, and would be exciting to see in Edmonton. I just want to make sure it's the right thing to do right now, and that we're able to do it right as it will be a big financial and time investment.

**Comment by MarkBennett** [comment]
@seanhealy that's an interesting idea. How would you describe Polyglot?

**Comment by seanhealy** [comment]
If you've ever been to a bar camp it's similar to that but tech focused instead of biz focused.

This is our site from last year. Being an un-conference the organizational overhead was pretty low.

http://ab.polyglotconf.com

**Comment by MHerszak** [comment]
@seanhealy all the sessions are open until the event? Are there any videos about it? My goal with the conf would be to attract companies and to solely talk about JS, best practice, lessons learned, etc.. I just looked at the Vancouver sessions and only one out of 20 was about JS. I get why this would be nice but it wouldn't fit into the scope of a JS meetup, or would it?

![cjkbiwbvaaa_x7v](https://cloud.githubusercontent.com/assets/4604432/16121248/cdf559b4-339f-11e6-93f2-acf3f0321036.jpg)

**Comment by MHerszak** [comment]
I would like to invite speakers to talk about JS related topics for this conf and I have the time and the drive to do it. A conference would be nice due to the environment (Edmonton) we live in. There are only a hand full that work with production ready code. I would like to educate others to work with JS. What I feel like is that it will be hard to receive "high quality"/"top notch" content. Hence, a one day conf would be a pilot to see if we could actually get it of the ground. I hope I am wrong.

**Comment by MarkBennett** [comment]
We need to start at the beginning here and decide if this is something the meetup wants to take on right now. I'm honestly skeptical that there's enough demand right now to make a conference feasible, given there are other less risky ways to bring companies and knowledge to Edmonton. Lets focus on better understanding what we'd hope to do at this conference, and what the costs would be, then raise it with our members in September. If it seems like we can get the numbers and funding we need to make it feasible, then let's do it!

**Comment by MarkBennett** [comment]
Let's table further discussion on this until we've got our priorities for next year sorted out. There are other ideas for worthwhile projects which could achieve similar goals. I've created issue #43 for this discussion.

For example, I'd like to start flying a speaker in once a quarter to talk about things like React or Angular best practices. This would be a lower risk way to get serious speakers out to Edmonton, and to start building the community we'd need to support a large JavaScript conference.

We could also look at teaming up with meetups in Calgary, Vancouver and elsewhere to spread out some of the costs and to access a larger pool of attendees.

All of these are good ideas, but will take time and money. Doing them all just isn't realistic, so it makes sense to invest our resources were we'll have the most success. To do this, we first need to decide on our priorities for the next year. Again, I'm not against the idea of a conference and don't want to dampen your enthusiasm, but we need to make sure we're getting the most bang for our buck.

**Comment by MHerszak** [comment]
I like the idea of flying in a high profile!

Question: what benefit has Calgary to team up with us in YEG? What benefit would they see to split cost? And why would we need to split cost? If we split cost for a high profile than the questions of where this would take place would remain and I don't want to drive to Calgary for 1.5h. This sounds very negative, I know. I just want to understand the reasoning :)

**Comment by MarkBennett** [comment]
I'm thinking we'd be splitting for a conference. Perhaps make it more of JS West or something, with rotating locations in Edmonton, Calgary, Vancouver? That would encourage all of us to promote each other which can't be bad, spread out the risk, and give us a much bigger potential budget.

**Comment by seanhealy** [comment]
Also don't want to be a downer but I I'd agree with @MarkBennett here. Think I'd prefer to focus on how we can make Exchange that much more amazing that spreading ourselves too thin. :)

**Comment by MHerszak** [comment]
JS West SOUNDS GREAT! But what are the benefits for Calgary and Vancouver? They already have a good community and it is actually us who need their help. Not the other way around. What is it that we could offer? I did all those talks at the UofA when I tried to get a couple professors together for a project. You need this one defining thing that most of us want. It would be so great to be promoted by Vancouver. But Vancouver doesn't need us to promote them. What is it we can offer? If we had a high profile we would have some leverage. The only company currently working hardcore with node is Hometribe. I can tell you at least 10 in Vancouver :) By the way, if we find that point we'd be able to leverage EJS to become great. But JS WEST is awesome!

**Comment by CAYdenberg** [comment]
I agree with @MarkBennett and @MHerszak that a conference is too much to take on right now. Let's focusing on upping the engagement with our current product (Meetup + website) and if the enthusiasm is there we could decide this later on.

Here's a crazy idea: we vote on our very best talk for the whole year, and send that person to give the their same talk at Calgary's JavaScript meetup. The Calgary meetup does the same. It would be a stepping stone toward collaboration on something bigger, and it would cost $, but much less than flying out some big shot. Feel free to poke holes.

**Comment by snostorm** [comment]
It would be cool to do it in a year or two once we get the base grown. For a few years I was helping organizing the annual Logicon conference (a science focussed event, 1-2 days of speakers but mostly local experts) and it takes a ton of work to line everything up!

**Comment by MarkBennett** [comment]
Agreed. This is a really exciting idea and not one we should lose sight of. Spending the next few years building the size of our audience and building relationships with potential speakers makes sense. We could.also take the time to run a few smaller events to get some practice dealing with things like ticketing and venue rentals.

**Comment by MarkBennett** [comment]
I really like this idea, but for now I'm going to close it. Let's get the sponsorship and infrastructure in place a bit more, then revisit in the new year!
