### ISSUE TITLE
Decide on objectives for 2016-17

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#43]
Now that the exec has been selected, I propose we start the next year by reviewing the feedback from our member survey and selecting objectives to focus on over the next year.

Our final deliverable would be:

1) A statement of our overall mission
2) A list of objectives we're going to do this year

To accomplish this, we need to:
- [x] review results of member survey
- [x] review results of sponsor survey
- [x] brainstorm our mission
- [x] agree on mission
- [x] brainstorm possible objectives
- [x] agree on objectives for this year

**Comment by MarkBennett** [comment]
I'm going to mark this a blocked until I'm able to complete my summary of the member survey in #19.

**Comment by MarkBennett** [comment]
Summarizing the member survey didn't take as long as I thought. Here's [the summary](https://docs.google.com/document/d/1QFR-3w-D8Wl5MlEfPnpBfqAyvXjlN7NzucMtznvFCe8/edit?usp=sharing), and [the raw results](https://docs.google.com/forms/d/1xHHaW64uVKBm0UYo_yctQnwoQYCqdvVtVASYHHz7lS4/edit#responses).

**Comment by MarkBennett** [comment]
Still blocked on sponsor survey.

**Comment by MarkBennett** [comment]
There are only two responses to the sponsor survey. Not going to summarize. Results here:

https://docs.google.com/forms/d/136u-YT5FeRzaG_o5FB5Iv1c6ylb8soDmWRlqcOCTt9M/edit?uiv=1#responses

I'll leave it open and summarize later if needed.

**Comment by MHerszak** [comment]
@MarkBennett I can't access the results.

**Comment by MarkBennett** [comment]
@MHerszak can you access the spreadsheet?

https://docs.google.com/spreadsheets/d/12FXq9c0mWGWQ-9Jnups1LCU6JBtfNqcF69_PlQqVblA/edit?usp=sharing

**Comment by MarkBennett** [comment]
From the ideas I see in member survey, I think it's clear that, "Our mission is to connect, inspire and educate the Edmonton JavaScript community."

In order to do this, I propose three objectives for the next year:

1) create a venue to showcase community members, jobs, organizations, events and projects in Edmonton
2) directly engage the Edmonton JavaScript community with leaders from projects shaping the way we work now and tomorrow 
3) increase the value of monthly talks by raising their quality and accessibility

Thoughts? I think these are specific and achievable, but still ambitious enough to push us and excite our sponsors and members.

**Comment by MHerszak** [comment]
I love those three points! From what I see, number 1 to 2 are within our "power". Number three will increase over time I hope. Maybe we should only focus on items we have an influence on?

**Comment by MarkBennett** [comment]
@mherzak I have plans for number three! 😉

I've been looking at what other meetups do, and some things we could do differently to raise quality are:
- plan out an anchor talk for each meetup at the start of the year
- enforce specific time limits for talks and for questions 
- help (or require) talks to be practiced in advance
- record all talks for reference 
- really promote hard recordings of our better talks so people see what they're missing 

There are other things we can do to, but these are the big ones that I think will make a big difference.

**Comment by MHerszak** [comment]
Those are good points. I need to work on my talking skills and would need some help with it. I am pro require practice in advance. Those talks can be recorded and analysed. I could do that since I am so close to StartUp, or the UofA.. or any location in downtown

**Comment by CAYdenberg** [comment]
@MarkBennett - I like those as objectives/core values. What do you mean by an anchor talk?

How do we feel about the beginner talks? Seems like they are important for the objectives as defined, but may be too basic for the most of the audience (who mainly identify as intermediate or higher). 

@MHerszak I'd be happy to help anyone with their speaking (as long we can find a time/place to meet). I have quite a bit of experience with public speaking going back way before I got into code, and it's one thing I'd like to get back into (hence joining the core team).

**Comment by MarkBennett** [comment]
@CAYdenberg one idea I was playing with was starting the meetup with a beginner talk or workshop, then moving on to the food and more advanced talks later. This way more advanced users could easily skip the stuff they were already familiar with. I definitely agree this is important, and based on the survey it looks like a lot of the membership agrees. We may want to follow up with the members to see which areas would benefit exploring most with beginners. Perhaps we could run it like a year long series which would end with all the basics covered?

Any ideas for the best ways to help our presenters prepare and improve the quality of their talks?

**Comment by MHerszak** [comment]
@MarkBennett a "simple" way of improving quality would be to give a general outline/guideline. Don't know if that would be to restricting?

Same when you write a paper.. first thing is to get an outline than details and results. Just a thought.

**Comment by MHerszak** [comment]
Same when you write a paper.. first thing is to get an outline than details and results. Just a thought.

**Comment by MarkBennett** [comment]
It's a good idea @mhersazk. We should definitely start encouraging (requiring?) speakers to do that.

**Comment by MarkBennett** [comment]
Does anyone else have feedback on the mission and objectives?

My only feeling is that each could tie more directly back to our mission of connecting, inspiring, and educating. Can we rework them a little to more directly connect to those?

**Comment by MarkBennett** [comment]
Perhaps something like this..

1) connect and inspire the community by showcasing community members, jobs, organizations, events and projects in Edmonton
2) educate and inspire the community by engaging the Edmonton JavaScript community with leaders from projects shaping the way we work now and tomorrow
3) better educate by increasing the quality and accessibility of our talks

Thoughts? They still feel a little wordy but seem more connected to the mission and cohesive as a whole.

**Comment by MarkBennett** [comment]
@caydenberg forgot to answer your question about anchor talk. It would be one main talk planned for each meetup throughout the year. This would help us ensure reliable speakers who've had a chance to rehearse and prepare, hopefully raising the bar for everyone who presents.

**Comment by MHerszak** [comment]
I am personally a one value one vision person. Your first bullet it on the dote and basically what I would want to see, too. The second bullet should come through bullet one. Connect and learn about best practice and/or lessons learned. I believe inspiration and education go hand in hand. I was never good in subjects that did not inspire me. Just my opinion :) Long story LONG, I would go with connect and work on that. It seems like this has been a neglected because I only see a handful of developers from a handful of companies and those barely give a talk. So, this should be a priority. Activate those developers and inspire them to give a talk about their best practices.

**Comment by MarkBennett** [comment]
You're totally right and inspiration being so important. It's also hard to figure out what will really inspire people as it's such a personal motivator too. For the purposes of planning the next year, perhaps the points need to be more specific so that it's clearer what each is trying to achieve? Reading them again, none of them are very measureable so gauging our success would be hard.  Let me take one more stab at it, this time with some metrics we can gauge..

1) connect and inspire the community by increasing the number of visitors to a community showcase on the web which includes noteworthy jobs, organizations, and projects in Edmonton
2) educate and inspire the community by engaging the meetup with at least one leader from projects shaping the way we work now and tomorrow every 3 months
3) better educate by increasing the quality and audience of our talks

Those all seem specific and measurable to me. I've tried to narrow them down to just the higher value parts or each. Thoughts? Are there specific enough and provide enough value? If no one has an issue with these I'd like to agree on them and we can start to move forward on the budget and fund raising.

**Comment by MHerszak** [comment]
This is good! Regarding number 2, how about we assign each exec for a specific topic/project? Or what do you mean with leader?

**Comment by abramhindle** [comment]
I guess I should've discussed this here, but I think we have to figure out what we do. Off the top of my head:
- Website update
- Slides for the meetup
- Updating meeting description
- Sponsors
- Food
- MC
- ...

**Comment by MarkBennett** [comment]
@abramhindle, are those tasks for each meetup or for the website? I'd like to keep the objectives fairly high level, then we can spin off each into an issue and break them down into the level of detail you're suggesting. Perhaps I can retool the first one to better capture that we want to improve how we use the website?

1) **connect** and **inspire** by increasing the number of visitors to a community showcase on the website
2) **educate** and **inspire** by engaging the meetup with at least one community leader from projects shaping the way we work now and tomorrow every 3 months (i.e. React core team member, Angular team member, npm maintainer, etc.)
3) better **educate** by increasing the quality and audience of our talks

The community showcase could include many things, for example noteworthy jobs, events, talks, and projects in Edmonton. It wouldn't include our meetups, but would instead push people to Meetup.com for the actual events.

Can we agree on these as objectives and I'll close this issue and spin up separate issues for each of these objectives so that we can break them down more?

**Comment by CAYdenberg** [comment]
I agree in principle that those are good objectives. Ready to discuss
actionable items in each category.

**Comment by MarkBennett** [comment]
That's great @caydenberg. Is everyone else ready to agree on these and move on?

**Comment by MarkBennett** [comment]
@ExchangeJS/organizers anyone object to these or can I record them and close this issue?

**Comment by MarkBennett** [comment]
I'll leave this open until the end of the week, then finalize these and close this off unless anyone objects. Thanks!

**Comment by MarkBennett** [comment]
Just a reminder that I'll be closing this end of day.

**Comment by MarkBennett** [comment]
To summarize, _"Our mission is to connect, inspire and educate the Edmonton JavaScript community."_

I've created an issue for each objective.

#49 **connect** and **inspire** by increasing the number of visitors to a community showcase on the website

#50 **educate** and **inspire** by engaging the meetup with at least one community leader from projects shaping the way we work now and tomorrow every 3 months (i.e. React core team member, Angular team member, npm maintainer, etc.)

#51 better **educate** by increasing the quality and audience of our talks

I'll use this off and we can move further discussion into each of these issues.

**Comment by snostorm** [comment]
Better late than never, but 👍
