### ISSUE TITLE
Propose a budget

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#44]
We need to work out a budget for the next year so we know how much money we need to raise to achieve our objectives for the year.

**Comment by MHerszak** [comment]
The basics are food for the meetups, correct? Everything else would be ontop, correct? How much did you spend for food?

**Comment by MarkBennett** [comment]
I'd like to work out some costs for new things we'd like to do, like bringing in speakers, perhaps setting up a hosted app instead of a static website, a budget for A/V, etc.

**Comment by MHerszak** [comment]
My two cents, start with the lower hanging fruit. I don't see anything wrong with a static website. The last update was February 5, 2015 and from what I notice most people don't even look at it. That is just time that should go into talking to speakers and figuring out how much they are. Before we do that we should get a catering and tech budget going. Am I missing something here? What was the food budget last year and what should it be this year? What does the static and small microphone cost and what the mixer/pult thingy you proposed? I don't see this being a big issue here. As soon as we have this number I can go and do some bell ringing with the right story.

**Comment by MarkBennett** [comment]
@MHerszak no big issues here. We just need to work out what we're doing then come up with the costing so we can go to sponsors asking for the right amount. Let's focus on #43 then this should follow pretty quickly from that.

**Comment by abramhindle** [comment]
Since the website doesn't get updated maybe what we need to do is identify recurring tasks. Mark likes to organize and make slides and all that but surely there's one of the board who want to take the web-chair job. Maybe we need to figure out what tasks we do have.

**Comment by MarkBennett** [comment]
Agreed @abramhindle. We need to decide on what our website is for, then how and who will maintain it.

**Comment by MHerszak** [comment]
@MarkBennett why don't we fully utilize the meetup page and a Facebook page? I have a feeling this would get more attention and is easier to share and update. Any thoughts? Having said this, I know we like to get our hands dirty .. but it is a meetup and this requires a different focus. We did all our discussions and posts in Munich through the MeetUp page and it worked perfectly. Just a thought

**Comment by MarkBennett** [comment]
We made the decision not to post events on Facebook or Google+ last year and make Meetup the sole source for events. It has worked out really well and I'd like to keep events on Meetup and direct users there from other pages like Facebook, Twitter, etc. I definitely agree with dropping the events listing from the website. In fact there's an issue somewhere to populate that event list from the Meetup API. #16  ~~I'm on my phone now but will find the link later.~~

In terms of bringing this back to the budget, we just need to decide if we need to include costs for any hosting we'd like to do, or if a static site hosted by GitHub is adequate. I'm inclined to include some hosting costs so that we can build a dynamic showcase of some sort as some community members, especially businesses, aren't comfortable using a pull request to add or update a job listing.

**Comment by MarkBennett** [comment]
I've also talked the Calgary meetup and they might be interested in assisting with setting up a job board or showcase that could be used by both meetups. Would need to follow up. Not sure if we'd share hosting or just source code.

**Comment by MarkBennett** [comment]
Why don't we table further discussion on the issue until we address #43 and can all agree on our objectives for the year? It seems like it will be much more productive once that's sorted out?

**Comment by MarkBennett** [comment]
Now that we have our objectives, I made a first pass at a budget. This will give us a sense of how much money we need to raise if we want to accomplish everything we need to throughout the year.

https://docs.google.com/spreadsheets/d/1TKd0UKCkeA9UUMVWNMDEES9yJocH1V4uMhSbkqed9Fo/edit?usp=sharing

You should all have access to edit it, as it's in the shared Google Drive folder but if you don't please let me know your Google address so I can add you.

**Comment by MarkBennett** [comment]
In case you're curious what I'm proposing for the swag line..

https://www.stickermule.com/products/die-cut-stickers

**Comment by MarkBennett** [comment]
If no one has any concerns with this, I think it's a reasonable budget to target in terms of sponsorship.

/cc @MHerszak @seanhealy @abramhindle

**Comment by seanhealy** [comment]
A bit random… I was bouncing some sticker ideas off of Mark the other day…

![](http://d.pr/i/pGGz.png)

We might also be able to use Collage Copy for stickers. They are right downtown.

**Comment by seanhealy** [comment]
@MarkBennett I think your food estimate is low. We've been spending more along the lines of ~$300 on food lately.

**Comment by seanhealy** [comment]
Also, I'm a bit out of the loop but do we need paid web hosting? :)

**Comment by MarkBennett** [comment]
Oh wow, I didn't realize that @seanhealy. That's a lot! That works out to $3000 a year for food. That's a lot of money we could be putting towards bringing in a speaker, prizes, etc. Any ideas on how we could bring that down closer to $150? We should still be able to get something decent in that price range.

I left the paid hosting in there as it's an option we're looking at. If we want to do things like setting up a job board or CMS we'll need something along those lines. We were able to get something running on a free Heroku dyno at the last hackup but the performance is obviously sub-optimal.

**Comment by MarkBennett** [comment]
@seanhealy cool idea with the sticker BTW. I was also mentioning the idea of having multiple complementary stickers at the hackup and it seemed like people really liked that idea. Why don't we move the sticker design into another issue as it's not really material to the budget?

I just setup #57 for this.

**Comment by MarkBennett** [comment]
I'd like to lock down the budget this week. I've updated with details for the hackup and pulled back a bit on paying for speakers.

https://docs.google.com/spreadsheets/d/1TKd0UKCkeA9UUMVWNMDEES9yJocH1V4uMhSbkqed9Fo/edit?usp=sharing

Unless there's any other feedback I'll finalize it and have it ready to present to sponsors on Monday.

**Comment by benzittlau** [comment]
Reviewed the budget and it seems reasonable to me.

**Comment by MarkBennett** [comment]
Thanks @benzittlau. I'm going to close this off.
