### ISSUE TITLE
Update the list of organisers on the website

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#46]

**Comment by CAYdenberg** [comment]
Who is @PawkaHub IRL? His profile pic is not quite ringing the bell.

**Comment by MarkBennett** [comment]
I'll see if I have his name in my notes @caseydenberg, but maybe @pawkahub can supply if he sees the notification?

**Comment by MarkBennett** [comment]
Thanks for taking this BTW! 😉

**Comment by MarkBennett** [comment]
I just talked to him via email and can confirm that Pieter Parker is @PawkaHub.

**Comment by MarkBennett** [comment]
Looks good to me. Thanks! :)
