### ISSUE TITLE
Connect and inspire by increasing the number of visitors to a community showcase on the website

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#49]

**Comment by CAYdenberg** [comment]
Similar things which exist:
- [Make Something Edmonton](https://www.makesomethingedmonton.ca/projects/)
- [Open Data Edmonton Apps](http://www.edmonton.ca/programs_services/apps_mobile/app-ets-live-to-go.aspx)

At the minimum we'd need to store a title, short description, and link to demo and GitHub repo for each project. This probably requires either a simple CMS (if people submit projects by email and we add them) or a Wiki-like system (if anyone can submit their own project).

A CMS may also be beneficial because we can more easily attach the PPT or Reveal.js docs (and videos! #28) for each meetup (I notice we've fallen pretty behind on that).

**Comment by MarkBennett** [comment]
That's exactly the kind of thing I'd like to see too @CAYdenberg. The biggest challenge I see is finding a way to maintain the content as time goes by. This suggests to me that we want to accept contributions from as many people as possible to make this easier. The projects, companies and jobs won't change too quickly, but there will be new talks and recordings of them added multiple times a month.

So I don't lose track of it, one other thing we might want to include in a CMS is a way to submit and gauge interest in potential talk ideas.

The decisions I see us needing to make are:

1) what exactly are we putting in the showcase?
2) who will be responsible for maintaining it?
3) what technology will power it?
4) will there be any on-going costs which would need to be included in the budget?

**Comment by MarkBennett** [comment]
I just created issue #52 so that we remember to ask members who they'd like to see at the meetup. We may want to do something quick and direct now, then feed our learnings from that back into the website.

**Comment by snostorm** [comment]
Perhaps it would be helpful to do a few hack-athon evenings or weekends in the coming few "off" months to work though choosing a tech stack, laying out a plan (MVP features and the followup steps we can take), building, etc.

A lot of planning can happen online but it sometimes it helps to kick some of these types of projects off by getting 2-4 people in a room for a few hours.

Thoughts on this approach? (We can still brainstorm until then.)

**Comment by MarkBennett** [comment]
That sounds good to me. We've got our normal meetup nights coming up, perhaps we could repurpose those for some hacking. Is anyone available?

**Comment by MHerszak** [comment]
@MarkBennett you want to use a Thursday night for a hackathon?

**Comment by snostorm** [comment]
I probably could with a bit more notice? Might be tied up this Thursday. But we could always break it out to a few sessions. (Might be nice to give a little notice and spam it out to a larger audience.)

The Jobber office could probably host a small group, unless we want to pick a pub or something.

**Comment by MarkBennett** [comment]
Would anyone be free the evening on June 7th to hack on this? If the Jobber offices have wifi we can all use that would work great for me.

/cc @ExchangeJS/organizers

**Comment by CAYdenberg** [comment]
Next Thursday (July 7th) would be better for me but I could do this Thursday too.

For tech my vote would be for Keystone, the major advantage being that it's full-stack JavaScript. You can define a "post type" as a souped-up Mongoose models and get an interface on the admin side for free. If you've ever worked with Django's admin it's very similar (but looks better).

I don't mind doing maintenance on it for next year, and taking on a chunk of the build (depending on what direction we want to go in).

**Comment by MarkBennett** [comment]
I vote for next Thursday too as it's easier for me. Need to confirm my babysitter but I'll be there if I can.

Also just checked out Keystone. I need to look at it a little more closely, but it looks great!

**Comment by CAYdenberg** [comment]
Are we getting together to hack this Thursday, and if so can we agree on a time/place?

**Comment by MarkBennett** [comment]
Yes. I'm just waiting to confirm that we can use the Jobber offices, then I'll announce on meetup.com. If we can't secure a space we can always work from home and connect via [Gitter](https://gitter.im/ExchangeJS/exchangejs.github.io).

**Comment by MarkBennett** [comment]
@snostorm can you confirm if we're able to use the Jobber offices Thursday night at 6:30?

**Comment by MarkBennett** [comment]
I just created the event,

I’m attending a Meetup with Startup Edmonton http://meetu.ps/e/BMvzv/FmTz/d

Space is limited, but I can make sure you get in if you RSVP. It is 95% certain it's at the Jobber offices on Jasper Ave, but I'll confirm tomorrow.
