### ISSUE TITLE
Educate and inspire by engaging the meetup with at least one community leader from projects shaping the way we work now and tomorrow every 3 months

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#50]
**educate** and **inspire** by engaging the meetup with at least one community leader from projects shaping the way we work now and tomorrow every 3 months (i.e. React core team member, Angular team member, npm maintainer, etc.)

**Comment by CAYdenberg** [comment]
Am I right in thinking we can't do this until we have a budget? Should we mark as blocked?

**Comment by MarkBennett** [comment]
I'm thinking we start by brainstorming what this means and coming up with some options. It could be everything from engaging with some projects via Github issues and PRs, to getting speakers in with hangouts, to flying them in. I'd also like to reach out to the membership to get some ideas for who they'd benefit from pursuing and start going after them now.

Some of these will require funds to accomplish. We should talk to some other meetups or events to see what costs are associated with bringing in these kinds of people. That could get fed back into the budget so we know how much we need to raise.

**Comment by MarkBennett** [comment]
I just created issue #52 so that we remember to ask members who they'd like to see at the meetup.

**Comment by snostorm** [comment]
I like the thought of engaging the wider community and agree it can happen in some budget thrifty ways at first. But it would be good to network with other meet ups and regional conferences because if somebody is already in Western Canada, it becomes much less costly to bring them up for an evening.

**Comment by MarkBennett** [comment]
That's a great idea @snostorm. I've spoken with the Calgary meetup a fair bit and could probably get them on board with this. Does anyone know anyone from the Vancouver meetup?

**Comment by abramhindle** [comment]
Google Hangout meetings are always possible. Toronto Perl Mongers holds google hangout meetings and I've been attending some of them for the past 5-6 years. Yes people still care about Perl :) It's a zero budget proposition. You can face the webcam to the audience and the MC can rely questions that aren't heard well.

**Comment by MarkBennett** [comment]
It definely looks like that's the way we're heading @abramhindle, especially given the low cost to start. There's more discussion of using Hangouts and what we need setup for September in issue #28.
