### ISSUE TITLE
Bring in a speaker from the React team

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#54]
Identify the best candidates from the react team to join us for a talk, then go after them until we get someone.

**Comment by MHerszak** [comment]
- Paul O’Shannessy - zpao
- Ben Alpert - spicyj
- Pete Hunt - petehunt

Those are the ones at the top of React's Github contributors list.

**Comment by MarkBennett** [comment]
Thanks @mherszak. I'll contact each of them via our Twitter.

**Comment by MHerszak** [comment]
I'd love to speak to Pete Hunt because he's also very knowledgeable in terms of Meteor!
