### ISSUE TITLE
Give stickers away to attendees and contributors

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#57]

**Comment by MarkBennett** [comment]
Ping @seanhealy

**Comment by seanhealy** [comment]
Thanks! :D

**Comment by seanhealy** [comment]
Will get some ideas up here for us think about.

**Comment by MarkBennett** [comment]
I was talking to some people about these stickers and a few things stuck:

1) they'll probably go on laptops so they should be re-usable and legible from a distance
2) people really liked the idea of a set of stickers which might interlock or somehow complement each other. I have seen other projects use hexagons, it might make sense to piggyback off a common size for these.
