### ISSUE TITLE
Exchange.js Mascot

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#58]
A lot of my favourite projects and communities have great mascots (Go, Linux, Android, etc.) Is anyone interested in designing a mascot we could use on the website, stickers, twitter, etc?

**Comment by nathany** [comment]
How about a [cute little doggie](https://www.kickstarter.com/projects/kcgreen/this-is-fine-plush-dog). 🙃

**Comment by MarkBennett** [comment]
Ha ha. That's awesome @nathany! Something just like that! :)
