### ISSUE TITLE
Recruit sponsors

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#59]
Over the next few months we need to recruit sponsors if we're hoping to make our budget for the year. Time to get started!
- [X] Create sponsorship package #20 
- [x] [Make a list of potential sponsors](https://docs.google.com/spreadsheets/d/1Hnq_OadnQ4DqON1BUQ9syxV9LUqokkE_4f615jUES3o/edit?usp=sharing)
- [x] Contact sponsors
- [ ] Collect commitments from sponsors

**Comment by MHerszak** [comment]
Hi Mark, did you start a list already somewhere?

**Comment by MarkBennett** [comment]
Not yet. Was going to start one today. In the main time why don't we just post names and contact details here?

**Comment by MarkBennett** [comment]
Here's the link to the list of potential sponsors:

https://docs.google.com/spreadsheets/d/1Hnq_OadnQ4DqON1BUQ9syxV9LUqokkE_4f615jUES3o/edit?usp=sharing

Please note this has confidential phone numbers and emails so please don't share publicly.

**Comment by MarkBennett** [comment]
Hey @MHerszak, I linked to a spreadsheet to keep track of who has been contacted. Feel free to add to and edit.

**Comment by MHerszak** [comment]
Hi, could you enter the contacts from last year, please? Those are the ones of the top of my head that deal with Javascript. I was thinking to maybe ask some recruiting for help? Those are the ones seeking talent. Just a thought.

**Comment by MarkBennett** [comment]
Sure.
