### ISSUE TITLE
Create a package for presenters

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#61]
This is intended to improve the quality of our talks. It could include things like tips and a checklist for our presenters, as well as some resources like presentation templates and logos for the meetup.

This issue is created as part of #51.

**Comment by MarkBennett** [comment]
@CAYdenberg @abramhindle any thoughts or ideas on this speaker package?

**Comment by CAYdenberg** [comment]
Sure thing. I may be able to devote some time to this this weekend. I'll probably create a new repo to sketch out my ideas.

Do we have a guideline length for talks? Something like 20 min + 10 min of questions.

**Comment by MarkBennett** [comment]
I'd say target 15 minutes talk, and 10 for questions but let speakers no
they can split the 25 minutes however they prefer. They should also know
that we're going to be timing them this year, that they're being recorded,
that they need to setup Google Hangouts in advance and have Wi-Fi. They
also need a bio, a headshot, and contact info. Finally they should be aware
that participating in Exchange.js they are agreeing to the code of conduct.

In speaking to our presenters for next month, they're using reveal.js and
Google Slides. I'm not sure what the third speaker is using but assume that
it's PowerPoint or Keynote.

Those are all the required things I can think of but I'm sure I'll have
some more feedback. Thanks for looking into this Casey. I'm swamped right
now and really appreciate it.
