### ISSUE TITLE
October 2016 Meetup

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#62]
Arrange and present the meetup.
## To Do
- [x] Arrange MC (Mark)
- [x] Arrange food
- [x] Add sponsor thank you to preroll
- [x] Setup notes [edit](https://github.com/ExchangeJS/exchangejs.com/blob/master/public/events/oct-2016/index.html), [view](https://www.exchangejs.com/events/oct-2016/)
- [x] Add sponsor thank you to notes
- [x] Update speakers in notes
- [x] Update events in notes
- [x] Update next meetup in notes
- [x] Update news and software releases in notes
- [x] Update job listings
- [x] Update introduction question
- [X] Setup Youtube Live event [https://www.youtube.com/watch?v=rNfuNelWhaA](https://www.youtube.com/watch?v=rNfuNelWhaA)
- [x] Mail out 3 day before meetup reminder
- [x] Tweet out 3 day before meetup link
- [x] Tweet out 1 day before meetup link
- [x] Tweet day of meetup link

/cc @ExchangeJS/organizers

**Comment by MarkBennett** [comment]
@seanhealy are you able to assist with the food still? Can you have something in place for this Thursday?

**Comment by MarkBennett** [comment]
I've created the notes:

https://github.com/ExchangeJS/exchangejs.com/blob/master/public/events/oct-2016/index.html

Contributions of events, jobs, or notes are welcome!

**Comment by CAYdenberg** [comment]
Will it help if I get there early? 
I can assist with food but it would help if I knew how we handled it in the past (payment, amount etc.)

**Comment by MarkBennett** [comment]
@caydenberg it wouldn't hurt as I'm sure there will be lots going on as we get back into the groove. This is the first one I'm going to try to live stream with YouTube so I'm anticipating some hiccups there.

**Comment by MarkBennett** [comment]
We're hoping to have food arranged in advance, and I should be there to pay in person so I think we're ok this time. I'll pay with my personal VISA then I can cut a cheque from the account I setup for Exchange.js once I get a receipt for the food.

**Comment by MarkBennett** [comment]
Need to add this job posting to our notes:

http://stackoverflow.com/jobs/124547/full-stack-javascript-developer-muzooka

UPDATE: DONE
