### ISSUE TITLE
Talks page

### ISSUE THREAD

**Issue by CAYdenberg** [ExchangeJS/exchangejs.github.io#70]
## To Do

- [x] Add link to YouTube page ("See all talks at our YouTube channel") 
- [ ] Add pagination
- [x] Add link on homepage to Talks page

**Comment by MarkBennett** [comment]
What do you think about adding a link to a screenshot instead of the green video icon? I'm generating a custom screenshot already, so adding them here wouldn't be difficult.

**Comment by CAYdenberg** [comment]
Yeah, that'd be better than a page of just text I would say.

**Comment by MarkBennett** [comment]
I'm going to close this for now as there are other things we can work on.
