### ISSUE TITLE
Fix webpack dev server

### ISSUE THREAD

**Issue by CAYdenberg** [ExchangeJS/exchangejs.github.io#71]

**Comment by MarkBennett** [comment]
@CAYdenberg Can you elaborate on what was up with this?

I'm working on some other parts of the site and can hack on this if it would be helpful. Just need to know what to do. ;)

**Comment by CAYdenberg** [comment]
Basically it hasn't worked at all since we added Express/Keystone. We need it to proxy the server generated instead of just watching local files.

I can take a look at it, I'm not just not a webpack expert so I thought I'd see if you knew what the deal was.

**Comment by MarkBennett** [comment]
@CAYdenberg hmm I see what you mean with the broken hot reloading. I'm pretty sure that there's a good way to proxy things through. I haven't set it up before but I can take a look at it.

**Comment by MarkBennett** [comment]
The latest Webpack has some proxy stuff that looks like it would be helpful in fixing this. I created issue #95 and will start work on this there.
