### ISSUE TITLE
Add YouTube Video Thumbnails

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#73]
I just found out that you can get YouTube thumbnails from a common url:

    https://img.youtube.com/vi/<insert-youtube-video-id-here>/hqdefault.jpg

Details at:

    http://stackoverflow.com/questions/2068344/how-do-i-get-a-youtube-video-thumbnail-from-the-youtube-api

/cc @CAYdenberg

**Comment by MarkBennett** [comment]
Here's an example of the thumbnal from this months meetup notes:

![April 2017 Notes Thumbnail](https://img.youtube.com/vi/xpt4njKfXCI/hqdefault.jpg)

**Comment by CAYdenberg** [comment]
Remind me about pagination next month as images range up to ~150kb
