### ISSUE TITLE
Announcement: Edmonton.py seeks JS talks

### ISSUE THREAD

**Issue by abramhindle** [ExchangeJS/exchangejs.github.io#74]
Announcement: Edmonton.py seeks JS talks

Edmonton.py http://edmontonpy.com is seeking speakers who want to talk about JS that is python compatible. That is anything regarding front-end JS dev that could be integrated into Django or Flask apps, or any python/js hybrids.

Please contact Edmonton.py organizers at mailto:info@EdmontonPy.com or on Twitter https://twitter.com/edmontonpy

If this could be jammed into community or news that'd be great. In exchange we offer a python talk on API stuff (REST/flask/etc.)

**Comment by ashiazed** [comment]
The idea is to do some cross talks, we could offer a talk of Python API design (Django/Flask) to the ExchangeJS community.

**Comment by MarkBennett** [comment]
This sounds like a great idea @abramhindle @laidibug. Any sense of timeframe? Are they aiming for September?

**Comment by CAYdenberg** [comment]
What topics and "level" are you looking for @laidibug? Most web devs know at least some JS and might be looking to level up to "modern" javascript, but the Python meetup is probably not all web folks.

**Comment by ashiazed** [comment]
@MarkBennett 
I had no time frame in mind, was gonna play it by ear and see if what kind of interest there is first.
But September sounds do-able.

@CAYdenberg  
Python meetup is definitely not all web folks, but we do have a small group. 
I wonder if a high-level overview would work good. Like how a Flask/Django API would work with javascript, but cover the javascript side of things. We could even schedule the Flask API/Django API one month before.

But modern javascript also sounds great, javascript has definitely gained some new goodies.

**Comment by MarkBennett** [comment]
@laidibug so we've finally got our ducks in a row and are incorporating a society to help out al the meetups. Would be great if you'd consider applying!

https://docs.google.com/forms/d/e/1FAIpQLSd71TKKsnMpBn25GZvaiJQqcC0oypaJY_SJTL2S0AYUJrn32g/viewform?usp=sf_link

**Comment by CAYdenberg** [comment]
Hey @laidibug I'm still up for giving that talk - if the python group is still interested let me know how we can connect. My contact info is on my profile page.
