### ISSUE TITLE
Select a society name

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#77]
[spreadsheet](https://docs.google.com/spreadsheets/d/1D0u1MjqH4Ti5ZIW-pARcQYzr6LiSW3ZOrdQnIKiIFyw/edit?usp=sharing)

**Comment by dlolsen** [comment]
Any movement on this?

**Comment by MarkBennett** [comment]
Hey @dlolsen. Not really. I'm working through some personal projects I've been neglecting over the last few months for the sake of the meetup.

The best way to contribute is probably to add some names to the spreadsheet and we can pick one next week.

**Comment by MarkBennett** [comment]
@ExchangeJS/organizers The bylaws are almost ready to circulate for approval (see #76 for the latest) which means we'll want to run our NUANS search soon. I'd like to lock the possible names down this week.

~~@dlolsen what do you need to run a NUANS search? Would next week be realistic for you?~~ Scratch this comment and see #78.

**Comment by MarkBennett** [comment]
I've setup a poll to vote on your favorite name. It closes this Friday at midnight:

https://exchangejs-voting.herokuapp.com/topic/598a89c5e113400004f86238

As part of testing voting systems for the new society, I've made a poll using an app called DemocracyOS that allows for voting and polling members of a group. It's not tied into Github but it's open source so that might be something we could contribute if we decided to use it.

**Comment by MarkBennett** [comment]
Results of the poll are in and it's a tie between "Dev Edmonton" and "YEGDev".

Unless there are strong objections I'm proposing we pick "Dev Edmonton" and carry on with the rest of the process. It's my preference because a) it's a clearer name for people that might not use Twitter, b) I didn't realize until recently but I actually registered devedmonton.com for another project a few years ago so we already own the domain.

I'll close this issue end of day if I don't hear otherwise. Thanks for all the help!

**Comment by dlolsen** [comment]
@MarkBennett I was on the fence between those two options, and while I think that YEG mostly transcends Twitter, Dev Edmonton seems to have a better ring; and hey, if we have the domain, lets go for it!

**Comment by MarkBennett** [comment]
@dlolsen thanks for the quick reply! ;)

**Comment by dlolsen** [comment]
@MarkBennett Does the DemocracyOS show what each person voted for? (For the record I voted YegDev, but am on board with Dev Edmonton).

**Comment by abramhindle** [comment]
Given you already have the domain name that's good. We don't have the twitter account but I don't see why that's super important.

**Comment by MarkBennett** [comment]
@dlolsen It doesn't seem to say who voted for what, though it does indicate who voted. There appear to be 6 votes and 7 participants so I'm wondering if commenting and not voting is enough to count as participating?

**Comment by MarkBennett** [comment]
Alright. "Dev Edmonton" it is. Closing.
