### ISSUE TITLE
Do a NUANS search to prove our name is availability

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#78]

**Comment by dlolsen** [comment]
I can do this once we decide on name!

**Comment by MarkBennett** [comment]
@dlolsen hoping to lock down the name this week (see #77) to coincide with bylaws being sent out. What do you need to do the NUANS search?

**Comment by dlolsen** [comment]
@MarkBennett The NUANS search can be done anytime, but is only valid for 90 days. All I need is the name we want, and to be sure we're within 90 days of incorporating.

It can also be done concurrent to registering the society which I can help with too; however, I'd say that if we decide on the name prior to being ready to incorporate I might as well just go ahead and do the NUANS search at that time.

**Comment by MarkBennett** [comment]
Ok. Thanks @dlolsen. Looks like we need to decide on that name!

**Comment by MarkBennett** [comment]
@dlolsen with the bylaws finished (see #76) I think it's time to do our NUANS search. Are you able to run this and get a receipt so we can pay you back?

**Comment by dlolsen** [comment]
@MarkBennett I'll get it done and keep the receipt!

We have to choose a legal entity for the name. Choices as follows: 

- Society
- Association
- Club
- Foundation
- Institute
- Guild
- Fellowship
- League
- Committee
- Council
- Board
- Centre
- Bureau
- Group
- Pool
- as well as the standard Inc. Corp. Ltd. (and long form versions)

I'd say "Association" seems the most relevant from the less corporate sounding ones.

Thoughts?

**Comment by MarkBennett** [comment]
Thanks @dlolsen!

"Dev Edmonton Society" is what's in the bylaws, but "Dev Edmonton Association" is fine too. Maybe do Society with Association as the alternate if they'll let us? I seem to remember we can include 2 or 3 in the NUANS search.

**Comment by dlolsen** [comment]
@MarkBennett If bylaws say Society, that's fine. I don't think it matters. As a matter of practice it seems common to omit the legal entity in colloquial use anyway. If they allow alternates I'll put Association too.

**Comment by dlolsen** [comment]
@MarkBennett I submitted the request with "Society". There wasn't a place for a 2nd option. I'll let you know when it comes through.

**Comment by MarkBennett** [comment]
Emails with search received. I've added these to the incorporation folder in Drive.
