### ISSUE TITLE
Move all questions from meetup to drinks

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#82]
I've been thinking a lot about what we can do to normalize the length of the meetup. The meetup length is one of the most frequently cited ways we could improve the monthly meetups.

One option I see for doing this is to eliminate questions after the talk. Instead, speakers would be encouraged to:

a) share their contact information during the presentation
b) connect the audience with the larger community for help
c) come and answer questions at drinks

The disadvantage to doing this is that we lose the interactivity during the talks, but it makes it simple for the audience to know how to connect and ask questions later. We may want to start doing a regular "roundtable" segment to make up for this.

Thoughts? I'd like to make a decision before August so speakers have time to prepare.

**Comment by AmeliaBR** [comment]
I don't like the idea of making "Drinks" an essential part of learning and interaction.  Some people won't want to come to a bar even if it starts a half hour earlier.

I also personally find the conversations at the end of presentations one of the more interesting / informative parts of the meetup.  There does need to be some management of the total time, but it would be a shame to lose that.  I like the idea of having dedicated roundtable sections, but that does sound like something that needs extra organizational power.

**Comment by MarkBennett** [comment]
@AmeliaBR good points. My motivation for moving the questions was to encourage people to come for drinks, and to build up some kind of online dialog on issues between the meetups. Perhaps a compromise on this would be to agree that all talks have a fixed length of time for questions, say ten minutes, then move the rest to drinks and online.

I think I'll pull the idea of a round table out of this issue and explore that on its own merits in another issue. I really like the idea of making these a more regular part of what we do as it allows experts with more constraints on their time a lower investment way to be involved.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by christiannaths** [comment]
Personally, I like the Q&A part of the talks quite a bit – it gives me a chance to hear questions/comments/concerns that I didn't think to ask myself. Limiting the amount of time given to any one topic makes a lot of sense to me

The only time I think I've felt Q&A could be improved is the odd time someone asks for help about a specific issue they're dealing with in their own codebase. I'd be in favor of requiring those types of questions being done async.

**Comment by Estyn** [comment]
I like the Q&A, but it does drag on sometimes.  A fixed length Q&A makes sense to me. 5 min for questions anything more can be taken offline.

**Comment by MarkBennett** [comment]
So it sounds like concensus is that Q & A in small amounts is good.

Will try going with 5 minutes of questions and reevaluate in 2018.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
