### ISSUE TITLE
Start doing speaker pre-interviews

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#86]
As we're constantly seeking to improve the quality of our talks, we've investigated using practice sessions, providing speaker resources, and more strictly controlling talk format. I'm proposing that along with this, we start some sort of formal speaker pre-interviews a month or so before each talk. These would serve to provide us with important information about the speaker, but also serve to coach the speaker on their talk, and provide another opportunity to encourage them to practice their talks in advance.

I found a good resource for doing podcast pre-interviews, but much of it would apply to the meetup as well.

http://transom.org/2016/art-pre-interview/

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CAYdenberg** [comment]
People prepare for talks in different ways and on different schedules, so I'm not sure as a speaker I would be down with this. A month is too early to help prepare a talk, and it's too late to screen/interview people who'd like to participate. Personally I'm in favour of the approach of: if someone wants to talk, let them, give them the Guidelines for Speakers we wrote which warns against the most common mistakes, and if it's not a good talk and they want to speak again, maybe it's time for unsolicited (but friendly) advice?

**Comment by MarkBennett** [comment]
@CAYdenberg interesting points. I agree that requiring this might come off as a little heavy handed. Really, I'm just hoping to find more ways to get people polishing up their talks. Practice and talking with others in advance helps me a lot, but I suppose we need to respect that not everyone's process is the same.

Perhaps we should commit to contacting all our speakers a week or two before they talk so they know we're available if they want, but not require that they do a pre-interview as I suggested.

We could also make more of an effort to follow up with speakers after their talks and find out what worked for them and what we could do better.

**Comment by MarkBennett** [comment]
I'm going to try contacting speakers a few weeks before the talks, as I basically do this already. I'll open a new issue if we decide to make this a formal part of organising.
