### ISSUE TITLE
Create new branding

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#88]
It's about time we updated our branding. We have multiple points of contact:

1) slidedecks
2) website
3) social media (Twitter, FB)
4) monthly emails
5) YouTube channel
6) pins or stickers

It would be great to have an updated logo, colours and typography. We'd then want to use that to update the resources above.

**Comment by MHerszak** [comment]
Do we have funding for a professional designer?

**Comment by MarkBennett** [comment]
We haven't done the budget yet so not sure. We've got a few pretty skilled designers who attend the Meetup, so I'm hoping that we can do this with our existing resources.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MarkBennett** [comment]
As discussed last night, I assigned this to @seanhealy.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
