### ISSUE TITLE
FOOD - ideas

### ISSUE THREAD

**Issue by dlolsen** [ExchangeJS/exchangejs.github.io#93]
## Food ~~Schedule &~~ Ideas
I've created a ~~Food Schedule~~ [Food Ideas](https://docs.google.com/spreadsheets/d/1L5JsGDs-1_Nk4bzJPo4KSpef463A8ED0RL9zII_KhW8/edit?usp=sharing) spreadsheet to get food organized going forward. I'm looking for ideas for food that has worked in the past, or things people would like to have, as well as any considerations that ought to be taken into account when setting up food (vegetarian options, allegies, etc.)

**The scheduled food for each Meetup will appear on the main Meetup planning spreadsheet (see Mark's comment below).

**Comment by MarkBennett** [comment]
Thanks for setting up that spreadsheet. I was wondering if we should merge the food in with the spreadsheet we use for planning speakers as the rows the two are almost the same. It could be the meetup planning spreadsheet or something. Here's the link...

https://docs.google.com/spreadsheets/d/1_FOG1K_fUbTlNvqT9hjihiXYt9AhPkZxW6tfZN858VU/edit?usp=drivesdk

Since you're the one managing food I'll let you decide. Maybe just let me know what you do so I can keep track.

**Comment by MarkBennett** [comment]
@dlolsen regarding food supplier advertising. It's an interesting idea if it would reduce our costs. I think we'd want to balance it with the amounts other sponsors are expected to contribute if they want recognition but we could probably work something out. Let's move that discussion to the issue on sponsorship for 2017-18.

**Comment by MarkBennett** [comment]
BTW, I'll sign in on my computer tonight and add in all of the places we got food from last year.

**Comment by MarkBennett** [comment]
Just updated the spreadsheet with past food providers that we'd use again, as well as special considerations ($200 budget and request from sponsors for local "non-pizza" as much as possible.)

**Comment by dlolsen** [comment]
@MarkBennett Yeah, totally makes sense to keep the scheduled food on the Meetup spreadsheet. We can move that over as things are confirmed. To keep that document clutter free I think it would make sense to still collect ideas & info on providers separately on the sheet I created. Thoughts?

**Comment by MarkBennett** [comment]
@dlolsen makes sense. The other sheet is most useful when I'm prepping notes and confirming details for a particular night.

**Comment by MarkBennett** [comment]
@dlolsen want me to close this?

**Comment by dlolsen** [comment]
@MarkBennett Been gone on vacation and then busy catching-up on work… I thought we might get some contribution to food ideas with it open, but yeah, let's close it off.

**Comment by MarkBennett** [comment]
Sounds good. Closing.
