### ISSUE TITLE
Test resolution for bylaws

### ISSUE THREAD

**Issue by MarkBennett** [ExchangeJS/exchangejs.github.io#96]
This is a example for testing a resolution for the new bylaws.

I resolve that tacos are awesome.

Like this issue if you support the resolution. Dislike if you don't. Comments below.

**Comment by MarkBennett** [comment]
Closing this.

In favour:

* Mark

Against:

* None

**Comment by MarkBennett** [comment]
Hey all, just testing this to see if using a GitHub issue would meet our requirements for voting pursuant to the act. Working on tweaking our bylaws but there are some things that might be required by the law which we can't work around.

**Comment by MarkBennett** [comment]
So the fact that almost anything can be editing after the fact (comments, issue description, reactions) means a GitHub issue isn't well suited to voting on society resolutions. Investigating using a forum or mailing list instead.

Closing.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dlolsen** [comment]
Could we build our own simple vote collecting app that fits the criteria? You know, to make more work;)

**Comment by MarkBennett** [comment]
@dlolsen I was thinking about that too. Perhaps we could start with an off the shelf solution like a Google Group then we could host something on Heroku if that wasn't enough.

**Comment by dlolsen** [comment]
@MarkBennett Probably good idea. I feel like Google Groups would have the same issue of being able to delete/edit stuff. There doesn't seem to be anything out there to fit this need… does there?

**Comment by MarkBennett** [comment]
@dlolsen I've just started looking so hard to say for sure. I wasn't under the impression that you couldn't edit posts on Google groups but I just checked and you're correct that they can be deleted which isn't what we really want.
