### ISSUE TITLE
Investopedia wants to buy beer

### ISSUE THREAD

**Issue by SteveReiter** [ExchangeJS/exchangejs.github.io#98]
Investopedia wants to sponsor us by buying a round of beer after each meetup, but this doesn't really help with our budget.

How should we handle this?

**Comment by MarkBennett** [comment]
I've been thinking a lot about this lately. Firstly, it's awesome that Investopedia is interested in supporting the meetup and I don't want to take that gesture for granted.

That said we've done donations in kind in the past and my sense is that I'd prefer to stick to the sponsorship structure we've laid out already. This seems fairer to other sponsors, and gives us the flexibility to spend the money at our discretion and as laid out in the budget. As we discovered before managing a significant number of these kind of donations in kind can also take significant time away from the execs other activities and distract from our priorities in the budget. As soon as we say yes to one request for this we're setting a precedent for the future making it harder to say no to others without playing favourites.

That said, we've polled members in the past on doing an open bar. I'll update this with a link to that survey but my memory was that we had minorities in favour and opposed to this, with a large majority without a strong preference either way.

If we do move forward with this and start providing a bar tab perhaps a reasonable compromise would be to commit to doing it within our existing sponsorship structure at the discretion of the exec. There are also parts of budget with a higher priority so we'd want to make sure those are funded first. As well we may want to see about adding a thank you to the sponsors on a sign we could put up at the bar or at the Meetup itself.

Thoughts?

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MarkBennett** [comment]
Don't want to come across as too much a downer here. Curious to hear what others think of this. We can talk on tomorrow nights call too. I know you can't make it @SteveReiter but if you leave your thoughts here I'll make sure they're shared with everyone else.

**Comment by SteveReiter** [comment]
I'm somewhat biased since I work for them but wearing my exchangejs hat I say we explain that we need sponsors to satisfy our budget and we can't give up limited sponsorship positions for entities that are not helping us meet the needs of our budget. They are certainly welcome to buy beer after and we can mention that they will be doing so at the event but I say we don't give them sponsorship perks unless they are helping us meet or budget.

Wearing my investopedia employee hat, I say we bump them up one sponsor tier if they are going to buy beer unless the higher tier is full.

I would be happy with anything in between those as well.

I already had an informal conversation with Kris (VP Engineering) and mentioned the difficulties around this so whatever we decide won't be totally unexpected.

**Comment by MarkBennett** [comment]
Thanks for your thoughts @SteveReiter let's see how everyone else feels tonight then make a decision so we can get an answer to Investopedia.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MarkBennett** [comment]
We spoke about this last night and all agreed that though our preference would be to get the money without any preconditions, it would be better to accept the money for a bar tab than not accept the money at all. To keep things fair we'll honour the support consistently with the way we acknowledge support from our other sponsors.
